project:
  title: "gsoc"
  render:
    - "*.qmd"
    - "!app/"
execute:
  freeze: auto

format: html
css: changes.css
from: markdown+emoji

mainfont: "Roboto Condensed"
monofont: "Roboto Mono"
linkcolor: "#043521"

number-sections: FALSE
toc: TRUE
toc-location: left
toc-title: "Contents:"
reference-location: margin
cap-location: margin